version: "3"

services:
  web:
    container_name: parser
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - 'redis:redis'
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./myapp:/app

  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'

  celeryworker:
    build: .
    hostname: worker
    volumes:
      - ./myapp:/app
    links:
      - 'redis:redis'
    depends_on:
      - redis
    command: celery -A app.celery worker --loglevel=info
